
# test against tthis version of Node.js
environment:
  matrix:
  #node.js
  - nodejs_version:"6"
#Initial scripts.(runs after repo cloning)
install:
  # Get stable version of nodejs or io.js
  - ps:Install-Product node $env:nodejs_version
  # install modules
  - npm install
# post_install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  #run tests
  - npm test
#Dont actually build.
build: off